### ISSUE TITLE
Add Makefile and CI

### ISSUE THREAD

**Issue by janiskemper** [SovereignCloudStack/csmctl#2]
## Description 

Adding our standard Makefile with testing, linting, releasing, etc. as well as a CI.

**Comment by kranurag7** [comment]
This is completed via https://github.com/SovereignCloudStack/csmctl/pull/7 and subsequent PRs. 
IMHO, this can be closed.

**Comment by janiskemper** [comment]
plz mention the appropriate issue in the PR if it exists ;)
