### ISSUE TITLE
look for packer and fail early if not found

### ISSUE THREAD

**Issue by aniruddha2000** [SovereignCloudStack/csmctl#73]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

this commit ensures we look for packer first and if it's not found in the PATH then we fail early giving an error message to the user.

Error message looks following

```shell
$ ./csmctl create
Error: packer binary is not installed: exec: "packer": executable file not found in $PATH
```

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- csmctl version: (use `csmctl version`)
- OS (e.g. from `/etc/os-release`):

**Comment by janiskemper** [comment]
as for example packer would be a dependency of a plugin, we can close it here
